# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.1.3"

package:
  name: gym-aloha
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/g/gym-aloha/gym_aloha-${{ version }}.tar.gz
    sha256: b794b246a2e6da6ce5f75e152f553fbd4412704bc217fe6311d0ede3bb72a75e

build:
  script: ${{ PYTHON }} -m pip install --no-deps --no-build-isolation .
  number: 0
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - mujoco >=3.0.0
    - dm-control >=1.0.15
    - gymnasium >=0.29.1
    # The package depends on imageio[ffmpeg], that we can translate (see https://github.com/imageio/imageio/blob/v2.37.0/setup.py#L92)
    # in depending on imageio, imageio-ffmpeg and psutil
    - imageio >=2.34.0
    - imageio-ffmpeg
    - psutil

tests:
  - python:
      imports:
        - gym_aloha
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A gym environment for ALOHA
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/huggingface/gym-aloha
  repository: https://github.com/huggingface/gym-aloha

extra:
  recipe-maintainers:
    - traversaro
